const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swaggerDocument.json';
const endpointsFiles = ['./src/modules/routes/routes.js'];

const doc = {
  info: {
    version: "1.0.0",
    title: "Hospital",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:8000",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "receptions"
    },
    {
      "name": "users"
    }
  ],
  securityDefinitions: {
    api_key: {
      type: "apiKey",
      name: "api_key",
      in: "header"
    },
    petstore_auth: {
      type: "oauth2",
      authorizationUrl: "https://petstore.swagger.io/oauth/authorize",
      flow: "implicit",
      scopes: {
        read_pets: "read your pets",
        write_pets: "modify pets in your account"
      }
    }
  },
  definitions: {
    usersReg: {
      login: "",
      password: "",
      passwordReveat: ""
    },
    usersAuth: {
      login: "",
      password: ""
    },
    paramsGetAllReceptions: {
      limit: "5",
      offset: "0",
      sortLable: "nameDoctor",
      sortDirection: "asc/desc",
      firstDate: "2021-08-01",
      lastDate: "2021-08-31"
    },
    paramsCreateNewReceptions: {
      nameUser: "Rustam",
      nameDoctor: "Doctor 1",
      date: "08/10/2021",
      complaint: "что то",
      limit: "5",
      offset: "0",
      sortLable: "nameDoctor",
      sortDirection: "asc/desc",
      firstDate: "2021-08-01",
      lastDate: "2021-08-31"
    },
    paramsEditReceptions: {
      nameUser: "Rustam",
      nameDoctor: "Doctor 1",
      date: "08/10/2021",
      complaint: "что то",
      limit: "5",
      offset: "0",
      sortLable: "nameDoctor",
      sortDirection: "asc/desc",
      firstDate: "2021-08-01",
      lastDate: "2021-08-31",
      _id: ""
    }
  }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./app.js');
})